version: '2'
services:
    auto4x-app:
        image: auto4x
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://auto4x-mysql:3306/auto4x?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    auto4x-mysql:
        extends:
            file: mysql.yml
            service: auto4x-mysql
